sudo: required

language: ruby

env:
  #- DOCKERFILE=tests/dockerfiles/DebianJessie.docker IMGNAME=debjess-grgsm
  #- DOCKERFILE=tests/dockerfiles/Ubuntu_15_04.docker IMGNAME=ubu15.04-grgsm
  - DOCKERFILE=tests/dockerfiles/Ubuntu_16_04.docker IMGNAME=ubu16.04-grgsm

services:
  - docker

before_install:
  - cat $DOCKERFILE > Dockerfile ; docker build -t $IMGNAME .

script:
  - docker run -it --rm $IMGNAME /src/test/tests/decode.sh
